# Generated by Django 5.2.1 on 2025-05-20 13:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dossiers_pme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteComptableDefaut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_compte', models.CharField(max_length=50, unique=True, verbose_name='Numéro de compte SYSCOHADA')),
                ('intitule_compte', models.CharField(max_length=255, verbose_name='Intitulé du compte SYSCOHADA')),
                ('type_compte', models.CharField(blank=True, choices=[('BILAN_ACTIF', 'Bilan - Actif'), ('BILAN_PASSIF', 'Bilan - Passif'), ('CHARGE', 'Compte de Résultat - Charge'), ('PRODUIT', 'Compte de Résultat - Produit'), ('TIERS_CLIENT', 'Tiers - Client'), ('TIERS_FOURNISSEUR', 'Tiers - Fournisseur'), ('TIERS_SALARIE', 'Tiers - Salarié'), ('TIERS_ETAT', 'Tiers - État'), ('TIERS_ASSOCIE', 'Tiers - Associé/Organisme Social'), ('TRESORERIE_ACTIF', 'Trésorerie - Actif'), ('TRESORERIE_PASSIF', 'Trésorerie - Passif'), ('AUTRE', 'Autre')], max_length=50, null=True, verbose_name='Type de compte')),
                ('nature_compte', models.CharField(choices=[('COLLECTIF', 'Collectif'), ('DETAIL', 'Détail/Mouvementable'), ('CENTRALISATEUR', 'Centralisateur')], default='DETAIL', max_length=50, verbose_name='Nature du compte')),
                ('sens_habituel', models.CharField(blank=True, choices=[('DEBIT', 'Débit'), ('CREDIT', 'Crédit')], max_length=10, null=True, verbose_name='Sens habituel du solde')),
                ('est_lettrable_par_defaut', models.BooleanField(default=False, verbose_name='Lettrable par défaut ?')),
                ('compte_parent_syscohada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_comptes_syscohada', to='comptabilite.comptecomptabledefaut', verbose_name='Compte parent SYSCOHADA')),
            ],
            options={
                'verbose_name': 'Compte Comptable SYSCOHADA (Défaut)',
                'verbose_name_plural': 'Comptes Comptables SYSCOHADA (Défaut)',
                'ordering': ['numero_compte'],
            },
        ),
        migrations.CreateModel(
            name='CompteComptablePME',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_compte', models.CharField(help_text='Numéro du compte spécifique à la PME.', max_length=50, verbose_name='Numéro de compte')),
                ('intitule_compte', models.CharField(max_length=255, verbose_name='Intitulé du compte')),
                ('type_compte', models.CharField(blank=True, choices=[('BILAN_ACTIF', 'Bilan - Actif'), ('BILAN_PASSIF', 'Bilan - Passif'), ('CHARGE', 'Compte de Résultat - Charge'), ('PRODUIT', 'Compte de Résultat - Produit'), ('TIERS_CLIENT', 'Tiers - Client'), ('TIERS_FOURNISSEUR', 'Tiers - Fournisseur'), ('TIERS_SALARIE', 'Tiers - Salarié'), ('TIERS_ETAT', 'Tiers - État'), ('TIERS_ASSOCIE', 'Tiers - Associé/Organisme Social'), ('TRESORERIE_ACTIF', 'Trésorerie - Actif'), ('TRESORERIE_PASSIF', 'Trésorerie - Passif'), ('AUTRE', 'Autre')], max_length=50, null=True, verbose_name='Type de compte')),
                ('nature_compte', models.CharField(choices=[('COLLECTIF', 'Collectif'), ('DETAIL', 'Détail/Mouvementable'), ('CENTRALISATEUR', 'Centralisateur')], default='DETAIL', max_length=50, verbose_name='Nature du compte')),
                ('sens_habituel', models.CharField(blank=True, choices=[('DEBIT', 'Débit'), ('CREDIT', 'Crédit')], max_length=10, null=True, verbose_name='Sens habituel du solde')),
                ('est_lettrable', models.BooleanField(default=False, verbose_name='Compte lettrable ?')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Compte actif ?')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes (spécifiques PME)')),
                ('compte_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_comptes_pme', to='comptabilite.comptecomptablepme', verbose_name='Compte parent (Plan PME)')),
                ('compte_syscohada_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comptabilite.comptecomptabledefaut', verbose_name='Compte SYSCOHADA de référence')),
                ('dossier_pme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_comptable_personnalise', to='dossiers_pme.dossierpme', verbose_name='Dossier PME')),
            ],
            options={
                'verbose_name': 'Compte Comptable PME',
                'verbose_name_plural': 'Comptes Comptables PME',
                'ordering': ['dossier_pme', 'numero_compte'],
                'unique_together': {('dossier_pme', 'numero_compte')},
            },
        ),
        migrations.CreateModel(
            name='JournalComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_journal', models.CharField(max_length=10, verbose_name='Code du journal')),
                ('libelle', models.CharField(max_length=100, verbose_name='Libellé du journal')),
                ('type_journal', models.CharField(choices=[('AC', 'Achats'), ('VE', 'Ventes'), ('BQ', 'Banque'), ('CA', 'Caisse'), ('OD', 'Opérations Diverses'), ('AN', 'À Nouveau')], max_length=10, verbose_name='Type de journal')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Journal actif ?')),
                ('compte_contrepartie_par_defaut', models.ForeignKey(blank=True, limit_choices_to=models.Q(('nature_compte', 'DETAIL'), models.Q(('type_compte', 'TRESORERIE_ACTIF'), ('type_compte', 'TRESORERIE_PASSIF'), ('numero_compte__startswith', '5'), _connector='OR')), null=True, on_delete=django.db.models.deletion.SET_NULL, to='comptabilite.comptecomptablepme', verbose_name='Compte de contrepartie par défaut (pour trésorerie)')),
                ('dossier_pme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journaux', to='dossiers_pme.dossierpme')),
            ],
            options={
                'verbose_name': 'Journal Comptable',
                'verbose_name_plural': 'Journaux Comptables',
                'ordering': ['dossier_pme', 'code_journal'],
                'unique_together': {('dossier_pme', 'code_journal')},
            },
        ),
        migrations.CreateModel(
            name='EcritureComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ecriture', models.DateField(verbose_name='Date de la Pièce')),
                ('numero_piece', models.CharField(blank=True, help_text='Numéro séquentiel ou manuel de la pièce dans le journal et la période.', max_length=50, verbose_name='N° Pièce')),
                ('libelle_piece', models.CharField(help_text='Libellé général de la pièce comptable.', max_length=255, verbose_name='Libellé Pièce')),
                ('numero_facture_liee', models.CharField(blank=True, help_text='Numéro de la facture client/fournisseur.', max_length=50, null=True, verbose_name='N° Facture')),
                ('reference_piece', models.CharField(blank=True, help_text='Autre référence pour la pièce (ex: Bon de commande).', max_length=100, null=True, verbose_name='Référence')),
                ('date_echeance_piece', models.DateField(blank=True, help_text="Date d'échéance globale de la pièce, si applicable.", null=True, verbose_name='Date Échéance (en-tête)')),
                ('montant_total_controle', models.DecimalField(blank=True, decimal_places=2, help_text='Montant total (ex: TTC facture) pour vérification. Optionnel.', max_digits=15, null=True, verbose_name='Montant Total Contrôle')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('dossier_pme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecritures', to='dossiers_pme.dossierpme')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ecritures', to='comptabilite.journalcomptable')),
            ],
            options={
                'verbose_name': 'Pièce Comptable',
                'verbose_name_plural': 'Pièces Comptables',
                'ordering': ['dossier_pme', '-date_ecriture', 'journal', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Tiers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_tiers', models.CharField(help_text='Code unique pour ce tiers dans ce dossier PME (ex: CL001, F-DURAND).', max_length=20, verbose_name='Code Tiers')),
                ('type_tiers', models.CharField(choices=[('CL', 'Client'), ('FO', 'Fournisseur'), ('SA', 'Salarié'), ('ET', 'État et Admin. Publiques'), ('OS', 'Organismes Sociaux'), ('DI', 'Divers (Opérations internes)'), ('AU', 'Autre Tiers')], default='AU', max_length=2, verbose_name='Type de Tiers')),
                ('nom_ou_raison_sociale', models.CharField(max_length=255, verbose_name='Nom / Raison Sociale')),
                ('prenom', models.CharField(blank=True, default='', max_length=100, verbose_name='Prénom (si particulier)')),
                ('adresse_ligne1', models.CharField(blank=True, default='', max_length=255, verbose_name='Adresse Ligne 1')),
                ('adresse_ligne2', models.CharField(blank=True, default='', max_length=255, verbose_name='Adresse Ligne 2')),
                ('code_postal', models.CharField(blank=True, default='', max_length=20, verbose_name='Code Postal')),
                ('ville', models.CharField(blank=True, default='', max_length=100, verbose_name='Ville')),
                ('pays', models.CharField(blank=True, default="Côte d'Ivoire", max_length=100, verbose_name='Pays')),
                ('telephone_principal', models.CharField(blank=True, default='', max_length=30, verbose_name='Téléphone Principal')),
                ('telephone_secondaire', models.CharField(blank=True, default='', max_length=30, verbose_name='Téléphone Secondaire')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Adresse Email')),
                ('site_web', models.URLField(blank=True, default='', verbose_name='Site Web')),
                ('rccm', models.CharField(blank=True, default='', max_length=50, verbose_name='RCCM')),
                ('compte_contribuable', models.CharField(blank=True, default='', max_length=50, verbose_name='N° Compte Contribuable (NCC)')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Tiers Actif ?')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date de création')),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('compte_comptable_associe', models.ForeignKey(blank=True, help_text='Compte du plan comptable PME (ex: 401xxx, 411xxx) à utiliser par défaut pour ce tiers.', limit_choices_to=models.Q(('numero_compte__startswith', '4'), ('nature_compte', 'DETAIL'), ('est_actif', True)), null=True, on_delete=django.db.models.deletion.SET_NULL, to='comptabilite.comptecomptablepme', verbose_name='Compte Comptable Général Associé')),
                ('dossier_pme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='dossiers_pme.dossierpme', verbose_name='Dossier PME')),
            ],
            options={
                'verbose_name': 'Tiers',
                'verbose_name_plural': 'Tiers',
                'ordering': ['dossier_pme', 'nom_ou_raison_sociale'],
                'unique_together': {('dossier_pme', 'code_tiers')},
            },
        ),
        migrations.CreateModel(
            name='LigneEcriture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_ligne', models.CharField(help_text='Libellé spécifique à cette ligne.', max_length=255, verbose_name='Libellé Écriture (ligne)')),
                ('date_echeance_ligne', models.DateField(blank=True, null=True, verbose_name='Date Échéance (ligne)')),
                ('lettrage_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Lettrage')),
                ('reference_ligne', models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence (ligne)')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Débit')),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Crédit')),
                ('ordre', models.PositiveIntegerField(default=0, editable=False, verbose_name='Ordre')),
                ('compte_general', models.ForeignKey(limit_choices_to={'est_actif': True, 'nature_compte': 'DETAIL'}, on_delete=django.db.models.deletion.PROTECT, to='comptabilite.comptecomptablepme', verbose_name='N° Compte Général')),
                ('ecriture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_ecriture', to='comptabilite.ecriturecomptable')),
                ('tiers_ligne', models.ForeignKey(blank=True, help_text='Si le compte général est un compte collectif (ex: 401, 411).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_ecriture_detail', to='comptabilite.tiers', verbose_name='N° Compte Tiers (ligne)')),
            ],
            options={
                'verbose_name': 'Ligne de Pièce Comptable',
                'verbose_name_plural': 'Lignes de Pièces Comptables',
                'ordering': ['ecriture', 'ordre', 'id'],
            },
        ),
        migrations.AddField(
            model_name='ecriturecomptable',
            name='tiers_en_tete',
            field=models.ForeignKey(blank=True, help_text='Tiers principal (Client/Fournisseur) pour la pièce.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecritures_en_tete', to='comptabilite.tiers', verbose_name='N° Compte Tiers (en-tête)'),
        ),
        migrations.CreateModel(
            name='TauxDeTaxe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_taxe', models.CharField(help_text='Code unique pour cette taxe dans ce dossier PME (ex: TVA18COL, AIRSI).', max_length=20, verbose_name='Code Taxe')),
                ('libelle', models.CharField(max_length=100, verbose_name='Libellé de la Taxe')),
                ('type_taxe', models.CharField(choices=[('COLLECTEE', "Taxe Collectée (sur Ventes/Chiffre d'Affaires)"), ('DEDUCTIBLE', 'Taxe Déductible (sur Achats/Frais/Immobilisations)'), ('AUTRE', 'Autre Taxe (ex: Retenues à la source, Impôts spécifiques)')], default='AUTRE', max_length=20, verbose_name='Type de Taxe')),
                ('taux', models.DecimalField(decimal_places=3, help_text='Entrez le taux en pourcentage, par exemple 18.00 pour 18% ou 1.25 pour 1,25%.', max_digits=6, verbose_name='Taux (en %)')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Taux Actif ?')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date de création')),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('compte_de_taxe', models.ForeignKey(help_text='Compte du plan comptable PME où cette taxe sera enregistrée (ex: 4431, 4452, 4421).', limit_choices_to=models.Q(('numero_compte__startswith', '4'), ('nature_compte', 'DETAIL'), ('est_actif', True)), on_delete=django.db.models.deletion.PROTECT, to='comptabilite.comptecomptablepme', verbose_name='Compte Comptable de la Taxe')),
                ('dossier_pme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taux_de_taxes', to='dossiers_pme.dossierpme', verbose_name='Dossier PME')),
            ],
            options={
                'verbose_name': 'Taux de Taxe',
                'verbose_name_plural': 'Taux de Taxes',
                'ordering': ['dossier_pme', 'type_taxe', 'code_taxe'],
                'unique_together': {('dossier_pme', 'code_taxe')},
            },
        ),
    ]
