# Generated by Django 5.2.1 on 2025-05-20 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecriturecomptable',
            name='date_echeance_piece',
            field=models.DateField(blank=True, null=True, verbose_name='Date Échéance (en-tête)'),
        ),
        migrations.AlterField(
            model_name='ecriturecomptable',
            name='libelle_piece',
            field=models.CharField(help_text='Libellé général de la pièce.', max_length=255, verbose_name='Libellé Pièce'),
        ),
        migrations.AlterField(
            model_name='ecriturecomptable',
            name='montant_total_controle',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Montant Total Contrôle'),
        ),
        migrations.AlterField(
            model_name='ecriturecomptable',
            name='numero_facture_liee',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='N° Facture'),
        ),
        migrations.AlterField(
            model_name='ecriturecomptable',
            name='numero_piece',
            field=models.CharField(blank=True, help_text='Numéro séquentiel ou manuel.', max_length=50, verbose_name='N° Pièce'),
        ),
        migrations.AlterField(
            model_name='ecriturecomptable',
            name='reference_piece',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence'),
        ),
        migrations.AlterField(
            model_name='ecriturecomptable',
            name='tiers_en_tete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecritures_en_tete', to='comptabilite.tiers', verbose_name='N° Compte Tiers (en-tête)'),
        ),
        migrations.AlterField(
            model_name='journalcomptable',
            name='compte_contrepartie_par_defaut',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('nature_compte', 'DETAIL'), models.Q(('type_compte__in', ['TRESORERIE_ACTIF', 'TRESORERIE_PASSIF']), ('numero_compte__startswith', '5'), _connector='OR')), null=True, on_delete=django.db.models.deletion.SET_NULL, to='comptabilite.comptecomptablepme', verbose_name='Compte de contrepartie par défaut (pour trésorerie)'),
        ),
        migrations.AlterField(
            model_name='ligneecriture',
            name='tiers_ligne',
            field=models.ForeignKey(blank=True, help_text='Si compte général collectif.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_ecriture_detail', to='comptabilite.tiers', verbose_name='N° Compte Tiers (ligne)'),
        ),
        migrations.AlterField(
            model_name='tauxdetaxe',
            name='code_taxe',
            field=models.CharField(help_text='Code unique pour cette taxe (ex: TVA18COL).', max_length=20, verbose_name='Code Taxe'),
        ),
        migrations.AlterField(
            model_name='tauxdetaxe',
            name='compte_de_taxe',
            field=models.ForeignKey(limit_choices_to=models.Q(('numero_compte__startswith', '4'), ('nature_compte', 'DETAIL'), ('est_actif', True)), on_delete=django.db.models.deletion.PROTECT, to='comptabilite.comptecomptablepme', verbose_name='Compte Comptable de la Taxe'),
        ),
        migrations.AlterField(
            model_name='tauxdetaxe',
            name='taux',
            field=models.DecimalField(decimal_places=3, help_text='Ex: 18.00 pour 18%.', max_digits=6, verbose_name='Taux (en %)'),
        ),
        migrations.AlterField(
            model_name='tauxdetaxe',
            name='type_taxe',
            field=models.CharField(choices=[('COLLECTEE', 'Taxe Collectée'), ('DEDUCTIBLE', 'Taxe Déductible'), ('AUTRE', 'Autre Taxe')], default='AUTRE', max_length=20, verbose_name='Type de Taxe'),
        ),
        migrations.AlterField(
            model_name='tiers',
            name='compte_comptable_associe',
            field=models.ForeignKey(blank=True, help_text='Compte du plan comptable PME (ex: 401xxx, 411xxx) à utiliser par défaut pour ce tiers.', limit_choices_to=models.Q(('nature_compte', 'DETAIL'), ('est_actif', True), models.Q(('type_compte__in', ['TIERS_CLIENT', 'TIERS_FOURNISSEUR', 'TIERS_SALARIE', 'TIERS_ETAT', 'TIERS_ASSOCIE']), ('numero_compte__startswith', '4'), _connector='OR')), null=True, on_delete=django.db.models.deletion.SET_NULL, to='comptabilite.comptecomptablepme', verbose_name='Compte Comptable Général Associé'),
        ),
    ]
