# Generated by Django 5.2.1 on 2025-05-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0002_alter_ecriturecomptable_date_echeance_piece_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligneecriture',
            name='jour',
            field=models.IntegerField(blank=True, null=True, verbose_name='Jour'),
        ),
        migrations.AddField(
            model_name='ligneecriture',
            name='numero_facture',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='N° Facture'),
        ),
        migrations.AddField(
            model_name='ligneecriture',
            name='numero_piece',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='N° Pièce'),
        ),
        migrations.AddField(
            model_name='ligneecriture',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence'),
        ),
    ]
