# Generated by Django 5.2.1 on 2025-05-29 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0003_ligneecriture_jour_ligneecriture_numero_facture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ligneecriture',
            name='reference_ligne',
        ),
    ]
