# Generated by Django 5.2.1 on 2025-05-16 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierPME',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_dossier', models.CharField(help_text='Nom officiel de la PME ou nom du dossier client.', max_length=255, verbose_name='Nom du dossier / Raison sociale')),
                ('numero_rccm', models.CharField(blank=True, help_text="Numéro d'immatriculation au Registre du Commerce et du Crédit Mobilier.", max_length=50, null=True, unique=True, verbose_name='Numéro RCCM')),
                ('numero_compte_contribuable', models.CharField(blank=True, help_text='Numéro de Compte Contribuable auprès de la DGI.', max_length=50, null=True, unique=True, verbose_name='Numéro de Compte Contribuable (NCC)')),
                ('adresse_siege', models.TextField(blank=True, null=True, verbose_name='Adresse du siège social')),
                ('telephone_standard', models.CharField(blank=True, max_length=30, null=True, verbose_name='Téléphone standard')),
                ('email_contact', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de contact principal')),
                ('site_web', models.URLField(blank=True, null=True, verbose_name='Site web')),
                ('forme_juridique', models.CharField(blank=True, choices=[('EI', 'Entreprise Individuelle'), ('SARL', 'SARL (Société à Responsabilité Limitée)'), ('SUARL', 'SUARL (Société Unipersonnelle à Responsabilité Limitée)'), ('SA', 'SA (Société Anonyme)'), ('SAS', 'SAS (Société par Actions Simplifiée)'), ('SNC', 'SNC (Société en Nom Collectif)'), ('SCS', 'SCS (Société en Commandite Simple)'), ('GIE', "GIE (Groupement d'Intérêt Économique)"), ('COOPERATIVE', 'Société Coopérative'), ('AUTRE', 'Autre')], max_length=20, null=True, verbose_name='Forme juridique')),
                ('secteur_activite', models.CharField(blank=True, max_length=255, null=True, verbose_name="Secteur d'activité principal")),
                ('date_creation_entreprise', models.DateField(blank=True, null=True, verbose_name="Date de création de l'entreprise")),
                ('date_debut_exercice_comptable', models.DateField(blank=True, help_text='Typiquement le 1er Janvier.', null=True, verbose_name="Date de début de l'exercice comptable en cours")),
                ('regime_fiscal_tva', models.CharField(blank=True, choices=[('RNI', "Réel Normal d'Imposition (TVA)"), ('RSI', "Réel Simplifié d'Imposition (TVA)"), ('IS', 'Impôt Synthétique (non assujetti TVA ou régime spécifique)'), ('FRANCHISE', 'Franchise en base de TVA'), ('EXONERE', 'Exonéré de TVA'), ('NON_APPLICABLE', 'Non Applicable'), ('AUTRE', 'Autre')], max_length=20, null=True, verbose_name='Régime fiscal / TVA')),
                ('centre_impots_rattachement', models.CharField(blank=True, max_length=100, null=True, verbose_name='Centre des Impôts de rattachement')),
                ('statut_dossier', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('ARCHIVE', 'Archivé'), ('PROSPECT', 'Prospect'), ('EN_CREATION', 'En création')], default='ACTIF', max_length=15, verbose_name='Statut du dossier')),
                ('notes_internes', models.TextField(blank=True, help_text="Informations réservées à l'usage interne du cabinet.", null=True, verbose_name='Notes internes')),
                ('date_creation_dossier_optimagest', models.DateTimeField(auto_now_add=True, verbose_name='Date de création du dossier dans OptimaGest')),
                ('date_derniere_modification', models.DateTimeField(auto_now=True, verbose_name='Date de dernière modification')),
                ('gestionnaire_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_geres', to=settings.AUTH_USER_MODEL, verbose_name='Gestionnaire principal du dossier')),
            ],
            options={
                'verbose_name': "Dossier PME (Côte d'Ivoire)",
                'verbose_name_plural': "Dossiers PME (Côte d'Ivoire)",
                'ordering': ['nom_dossier'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('numero_rccm__isnull', False)), fields=('numero_rccm',), name='unique_rccm_if_not_null'), models.UniqueConstraint(condition=models.Q(('numero_compte_contribuable__isnull', False)), fields=('numero_compte_contribuable',), name='unique_ncc_if_not_null')],
            },
        ),
    ]
